### ISSUE TITLE
Unable to add to HA via HACS

### ISSUE THREAD

**Issue by mectza** [masaccio/ha-kingspan-watchman-sensit#37]
Hi there folks!  I just tried to set up this integration vi HACS but ran into the following error banner:
![image](https://github.com/user-attachments/assets/e5e1696b-ad8d-4685-bfdb-3032e9f495b6)

Just curious if this is a known issue with 2024.12?

**Comment by masaccio** [comment]
Is this still a problem? It will take me a while to look.

**Comment by mectza** [comment]
Yes, it's still an issue, no rush on it though 🙂

**Comment by jfberry** [comment]
just got this today - is there a different way of setting it up?

**Comment by masaccio** [comment]
> just got this today - is there a different way of setting it up? (HA 2025.2)

No. It’s a bug in a library I need to access the Kingspan service. That bug hasn’t been fixed in a few weeks so I am working around it. Expect a fix this weekend.

**Comment by masaccio** [comment]
Please check v1.6.8 which I just published to fix #38

**Comment by jfberry** [comment]
<img width="584" alt="Image" src="https://github.com/user-attachments/assets/243d5ba6-9e0a-48ee-a3d1-5462fcdbe05c" />
Looks like it is working at least this far (with 2025.2.1).  I can't go further because my watchman sensit is still not delivered yet

**Comment by mectza** [comment]
> Please check v1.6.8 which I just published to fix [#38](https://github.com/masaccio/ha-kingspan-watchman-sensit/issues/38)

Great stuff, that's got it sorted - thanks a million!
